# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\硕士\Github搭建工程\demo_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1320, 880)
        MainWindow.setMinimumSize(QtCore.QSize(1320, 880))
        MainWindow.setMaximumSize(QtCore.QSize(1320, 880))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1320, 880))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("e:\\硕士\\Github搭建工程\\qt/images/background.png"))
        self.label_2.setObjectName("label_2")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(110, 90, 1100, 700))
        self.listView.setStyleSheet("QListView\n"
"{  \n"
"   background-color: rgba(255, 255, 255, 50%);\n"
"    border:1px solid darkkhaki;\n"
"}")
        self.listView.setObjectName("listView")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(150, 560, 981, 161))
        self.listWidget_2.setStyleSheet("QListWidget\n"
"{  \n"
"    background-color: rgba(255, 255, 255, 80%);\n"
"    border:1px solid darkkhaki;\n"
"\n"
"    \n"
"    font: bold 40px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:red; /* 字体颜色 */\n"
"    \n"
"    \n"
"\n"
"}")
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(840, 410, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(75, 173, 238); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    border-radius:16px; /* 边界圆滑 */\n"
"    font: bold 18px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:white; /* 字体颜色 */\n"
"    border:none;     /* 取消边界边框 */\n"
"    border: 2px solid rgb(255, 255, 255);   /* 添加2px的白色框 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 150, 0);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1000, 410, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(75, 173, 238); /*背景色*/ \n"
"    border-style: outset;    /* 边界内凹 */\n"
"    border-width: 1px;     /* 边边界宽度 */\n"
"    border-radius:16px; /* 边界圆滑 */\n"
"    font: bold 18px;     /* 字体大小 */\n"
"    min-width:2em;\n"
"    color:white; /* 字体颜色 */\n"
"    border:none;     /* 取消边界边框 */\n"
"    border: 2px solid rgb(255, 255, 255);   /* 添加2px的白色框 */\n"
"    \n"
"}\n"
"/* 鼠标经过改变按钮颜色 */\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 150, 0);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(980, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{ background-color: rgba(255,240,255,120); }QLineEdit:focus{background-color: rgb(255,255,255)}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(820, 185, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{ \n"
"    /*background-color: rgba(255,240,255,120); */\n"
"}\n"
"QLabel:focus\n"
"{\n"
"    background-color: rgb(255,255,255)\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(820, 237, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(980, 245, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{ background-color: rgba(255,240,255,120); }QLineEdit:focus{background-color: rgb(255,255,255)}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 120, 640, 400))
        self.label_5.setStyleSheet("QLabel\n"
"\n"
"{  \n"
"    background-color: rgba(255, 255, 255, 80%);\n"
"    border:1px solid darkkhaki;\n"
"}")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(820, 289, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(980, 290, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{ background-color: rgba(255,240,255,120); }QLineEdit:focus{background-color: rgb(255,255,255)}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "上传图片"))
        self.pushButton_3.setText(_translate("MainWindow", "单张识别"))
        self.label_3.setText(_translate("MainWindow", "牧 场 属 地 ："))
        self.label_4.setText(_translate("MainWindow", "牧 场 编 号 ："))
        self.label_6.setText(_translate("MainWindow", "保 存 文 件 ："))
